# Generated by Django 5.0.6 on 2025-02-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=10000)),
                ("tag", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="person",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
