# Generated by Django 5.0.6 on 2025-02-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reels", "0003_reels_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonPercent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.CharField(max_length=10000)),
                ("topic", models.CharField(max_length=255)),
                ("watch_percent", models.IntegerField(default=0)),
            ],
        ),
    ]
